name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Run only on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dynamic versioning plugin
        run: poetry self add poetry-dynamic-versioning[plugin]
      - name: Build Python package
        run: poetry build -f sdist -o dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
