name: Tests and coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements-tests.txt
        pip install coverage pytest pytest-cov
        pip install .
    - name: Run tests and coverage
      run: |
        pytest ./tests/ --cov=./systole/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
